# Generated by Django 5.1.5 on 2025-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
