# Generated by Django 5.1.5 on 2025-03-03 20:11

import cloudinary.models
import users_sys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[users_sys.models.file_validation], verbose_name='image'),
        ),
    ]
