# Generated by Django 5.1.5 on 2025-03-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baskets',
            name='products',
        ),
        migrations.CreateModel(
            name='ItemBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.baskets')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_basket', to='shop.products')),
            ],
        ),
    ]
