# Generated by Django 5.1.5 on 2025-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
