# Generated by Django 5.1.5 on 2025-05-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orders_total_price'),
        ('shop', '0002_remove_baskets_products_itembasket'),
    ]

    operations = [
    ]
