# Generated by Django 5.1.5 on 2025-01-29 17:04

import cloudinary.models
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[shop.models.file_validation], verbose_name='image'),
        ),
    ]
