# Generated by Django 5.1.5 on 2025-05-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_merge_20250501_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='products',
            field=models.ManyToManyField(related_name='basket', to='shop.products'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('framed', 'Замовлення оформлено'), ('transit', 'Доставляється'), ('delivered', 'Доставлено'), ('received', 'Отримано'), ('canceled', 'Скасовано')], default='framed', max_length=20),
        ),
    ]
