# Generated by Django 5.1.5 on 2025-02-23 17:39

import cloudinary.models
import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='character',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[shop.models.file_validation], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.products'),
        ),
    ]
