# Generated by Django 5.1.5 on 2025-05-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_baskets_products_alter_orderitems_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baskets',
            options={'permissions': [('add_product_to_busket', 'Add product to busket')]},
        ),
    ]
