# Generated by Django 5.1.5 on 2025-05-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('add_review_who_but_it', 'Add review who buy it')]},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.comment'),
        ),
    ]
