# Generated by Django 5.1.1 on 2025-05-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_reviews_options_alter_reviews_comment'),
        ('users_sys', '0002_shopprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discounts'),
        ),
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users_sys.shopprofile'),
        ),
    ]
