# Generated by Django 5.1.5 on 2025-06-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_products_price_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baskets',
            name='products',
        ),
        migrations.AddField(
            model_name='itembasket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('framed', 'Замовлення оформлено'), ('transit', 'Доставляється'), ('delivered', 'Доставлено'), ('received', 'Отримано'), ('canceled', 'Скасовано')], default='framed', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.categories'),
        ),
    ]
