# Generated by Django 5.1.5 on 2025-06-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_baskets_products_itembasket_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.baskets'),
        ),
        migrations.AlterField(
            model_name='itembasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.products'),
        ),
    ]
